version: '3'

services:
    powerfitness-ma: 
        build:
            context: .
            dockerfile: ../powerfitness-ma/Dockerfile # path to dockerfile
        image: powerfitness-ma
        container_name: powerfitness-ma
        volumes:
            - web-root:/usr/src/app/dist
    powerfitness-ms: 
        build:
            context: .
            dockerfile: ../powerfitness-ms/Dockerfile # path to dockerfile
        image: powerfitness-ms
        container_name: powerfitness-ms
        restart: unless-stopped
        networks:
            - app-network
    nginx:
        image: nginx:mainline-alpine
        container_name: nginx
        restart: unless-stopped
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - web-root:/var/www/html
            - ./nginx-conf:/etc/nginx/conf.d
            - certbot-etc:/etc/letsencrypt
            - certbot-var:/var/lib/letsencrypt
            - dhparam:/etc/ssl/certs
        depends_on:
            - powerfitness-ms
        networks:
            - app-network
    certbot:
        image: certbot/certbot
        container_name: certbot
        volumes:
            - certbot-etc:/etc/letsencrypt
            - certbot-var:/var/lib/letsencrypt
            - web-root:/var/www/html
        depends_on:
            - nginx
        command: certonly --webroot --webroot-path=/var/www/html --email catelynjscholl@gmail.com --agree-tos --no-eff-email --staging -d powerfitness.app  -d www.powerfitness.app

volumes:
    certbot-etc:
    certbot-var:
    web-root:
        driver: local
        driver_opts:
            type: none
            device: /home/cjscholl/dev/powerfitness-ma/dist/ #todo
            o: bind
    dhparam:
        driver: local
        driver_opts:
            type: none
            device: /home/cjscholl/dev/dhparam/
            o: bind
    
networks:
    app-network:
        driver: bridge